# Generated by Django 5.0.6 on 2024-08-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': '商品カテゴリー',
                'verbose_name_plural': '商品カテゴリー',
            },
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'カート', 'verbose_name_plural': 'カート'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'カートアイテム', 'verbose_name_plural': 'カートアイテム'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '注文履歴', 'verbose_name_plural': '注文履歴'},
        ),
    ]
